version: '2'
services:
    final-mongodb:
        container_name: final-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/final/mongodb/:/data/db/
